services:
  - type: web
    name: expense-tracker-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: DB_HOST
        value: bc0zu1dvwtgbqosunjap-mysql.services.clever-cloud.com
      - key: DB_USER
        value: ufidimjge9irtb6p
      - key: DB_PASSWORD
        value: nvi8yaE2ZI25DyRrIbLt
      - key: DB_NAME
        value: bc0zu1dvwtgbqosunjap
      - key: DB_PORT
        value: 3306


        value: your-secure-secret-key-here      - key: JWT_SECRET      - key: JWT_SECRET
        value: your-secure-secret-key-here