services:
  - type: web
    name: expense-tracker
    env: node
    buildCommand: ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: bc0zu1dvwtgbqosunjap-mysql.services.clever-cloud.com
      - key: DB_USER
        value: ufidimjge9irtb6p
      - key: DB_PASSWORD
        value: nvi8yaE2ZI25DyRrIbLt
      - key: DB_NAME
        value: bc0zu1dvwtgbqosunjap
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        value: your-secure-secret-key-here